name: Push commit to schema registry

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push to schema registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1.18.0
        with:
          github_token: ${{ github.token }}

      - name: Push to schema registry
        uses: bufbuild/buf-push-action@v1.1.1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
